/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entidades.Helado;
import java.awt.Image;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class frmHeladoConFoto extends javax.swing.JInternalFrame {

    private static int cantidad;
    private static String rutaDeArchivo;
    /**
     * Creates new form frmHeladoConFoto
     */
    public frmHeladoConFoto() {
        initComponents();
        if (cantidad == 1) {
            throw new ArithmeticException();
        }

        this.cantidad = 1;
    }

    public static boolean PuedoCrearOtra() {

        boolean retorno = false;
        if (cantidad == 0) {
            retorno = true;
        }

        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreHelado = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtImagen = new javax.swing.JTextField();
        btnBucarImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCantidadDisponible = new javax.swing.JLabel();
        txtCantidadDisponible = new javax.swing.JTextField();
        lblKilos = new javax.swing.JLabel();

        setTitle("Nuevo Helado");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtNombreHelado.setToolTipText("Ingrese nombre del nuevo helado.");
        txtNombreHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHeladoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtImagen.setToolTipText("Ingrese la imagen del helado.");

        btnBucarImagen.setText("...");
        btnBucarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarImagenActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        jLabel1.setText("Ruta:");

        lblCantidadDisponible.setText("Cantidad disponible:");

        lblKilos.setText("Kilos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidadDisponible)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lblKilos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombreHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnBucarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreHelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBucarImagen)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDisponible)
                    .addComponent(txtCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKilos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBucarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBucarImagenActionPerformed
        int respuesta;
       
        String nombre;
        String exten=".jpg";

        JFileChooser VentanaArchivos = new JFileChooser();
        respuesta = VentanaArchivos.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            rutaDeArchivo = VentanaArchivos.getSelectedFile().getPath();
         
            this.setFoto(rutaDeArchivo);
            
            
            File archivoBase = new File(rutaDeArchivo);
            exten = exten.substring(exten.length()-3);
            
            nombre = VentanaArchivos.getSelectedFile().getName(); 
            nombre="/img/"+txtNombreHelado.getText()+"."+exten;
            File ficheroDestino = new File( "./src"+nombre);
            archivoBase.renameTo(ficheroDestino);
            txtImagen.setText(nombre); 
            /*
            archivoBase.renameTo(ficheroDestino);
            nombre ="/img/" + VentanaArchivos.getSelectedFile().getName();
            exten = exten.substring(exten.length()-3);
            nombre="/img/"+txtNombreHelado.getText()+"."+exten;
            txtImagen.setText(nombre);   
            File archivoBase = new File(rutaDeArchivo);
            File ficheroDestino = new File("/src"+txtImagen.getText());
          
            
            /*
            File archivoBase = new File(ruta);
            File ficheroDestino = new File(nombre);
            archivoBase.renameTo(ficheroDestino);*/

        }

    }//GEN-LAST:event_btnBucarImagenActionPerformed
    
    
    public void setFoto(String ruta) {
        ImageIcon img = new ImageIcon(ruta);
        Image imagn = img.getImage();
        imagn.getScaledInstance(155, 140, WIDTH);
        ImageIcon imagen = new ImageIcon(imagn);
        lblImagen.setIcon(imagen);
        lblImagen.setSize(155, 140);
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.cantidad = 0;
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.cantidad = 0;

    }//GEN-LAST:event_formInternalFrameClosing

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Helado h = new Helado();

        if ((txtNombreHelado.getText().equals("")) || (txtImagen.getText().equals("")) || (txtCantidadDisponible.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
        } else {
            h.setSabor(txtNombreHelado.getText());
            /*
            File archivoBase = new File(rutaDeArchivo);
            File ficheroDestino = new File("/src"+txtImagen.getText());
            archivoBase.renameTo(ficheroDestino);*/
            h.setCantidad(Integer.parseInt(txtCantidadDisponible.getText()));
            h.setRuta(txtImagen.getText());
            Helado.guardarUnHelado(h);
    
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHeladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHeladoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBucarImagen;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidadDisponible;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblKilos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCantidadDisponible;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombreHelado;
    // End of variables declaration//GEN-END:variables
}
